name: 'Hello World'
description: 'Greet someone'
author: 'ShantanuDash'
inputs:
      file-name:
        description: 'Name of the input file(with extention)'
        default: 'ip.fdf'
        required: true
        
      dir-name:
        description: 'Name of the directory(folder) input files'
        default: 'ip'
        required: true
        
      out-name:
        description: 'Name of the output file'
        default: 'ip.out'
        required: true

runs:
  using: "composite"
  steps:
    - name: Check vars
      run: echo "jdjhugh" ${{ inputs.dir-name }} "${{ inputs.file-name }}" "${{ inputs.out-name }}"
      shell: bash
    - name: Create Output Directory
      run: mkdir ${{ inputs.dir-name }}
      shell: bash
      
    - name: Install Siesta
      run: |
        git clone https://gitlab.com/siesta-project/siesta.git
        cd siesta/Obj/
        sh ../Src/obj_setup.sh
        make
      shell: bash
      
    - name: Copy siesta
      run: |
        pwd
        cp siesta/Obj/siesta ${{ inputs.dir-name }}/
      shell: bash  

    - name: Calculation
      run: |
        cd ${{inputs.dir-name }}/
        ls
        ./siesta < ${{ inputs.file-name }} | tee ${{ inputs.out-name }}
      shell: bash
