name: 'siesta-action'
description: 'This action downloads the latest stable version of Siesta and runs your DFT calculations in GitHub Actions'
author: 'ShantanuDash'
inputs:
      file-name:
        description: 'Name of the input file(with extention)'
        default: 'ip.fdf'
        required: true
        
      dir-name:
        description: 'Name of the directory(folder) input files'
        default: 'ip'
        required: true
        
      out-name:
        description: 'Name of the output file'
        default: 'ip.out'
        required: true
      time:
        description: 'Timeout Time'
        default: 'i6m'
        required: true

runs:
  using: "composite"
  steps:
    - name: Check vars
      run: echo "jdjhugh" ${{ inputs.dir-name }} "${{ inputs.file-name }}" "${{ inputs.out-name }}"
      shell: bash
    - name: Install Siesta
      run: |
        git clone https://gitlab.com/siesta-project/siesta.git
        cd siesta/Obj/
        mv gfortran.make arch.make
        sh ../Src/obj_setup.sh
        make
      shell: bash
      
    - name: Copy siesta
      run: |
        pwd
        cp siesta/Obj/siesta ${{ inputs.dir-name }}/
      shell: bash  

    - name: Calculation
      run: |
        cd ${{inputs.dir-name }}/
        ls
        timeout --foreground ${{ inputs.time }} ./siesta < ${{ inputs.file-name }} | tee ${{ inputs.out-name }}
        RESULT="$?"
        if [ "$RESULT" != "0" ]; then
        exit 0
        fi
      shell: bash

